### ISSUE TITLE
Link to blog post url

### ISSUE THREAD

**Issue by mrfearless** [naksyn/DojoLoader#1]
The link in the readme to the blog post: https://www.naksyn.com/cobalt%20strike/2024/04/15/raising-beacons-without-UDRLs-teaching-how-to-sleep.html shows as 404 Not Found

This appears to be the correct url: https://www.naksyn.com/cobalt%20strike/2024/07/02/raising-beacons-without-UDRLs-teaching-how-to-sleep.html

**Comment by naksyn** [comment]
thanks, fixed
