### ISSUE TITLE
Q: oldbase seems always equals to lpBase

### ISSUE THREAD

**Issue by nstasy** [naksyn/DojoLoader#2]
memoryloader.c

    DllPayload.startOfMappedPE = lpBase;
    oldbase = DllPayload.startOfMappedPE;
    ……
    LONGLONG lBaseDelta = (PBYTE)pMemModule->lpBase - (PBYTE)oldbase;

**Comment by naksyn** [comment]
Not an issue. If delta is zero do not perform relocations, otherwise it performs relocations.

**Comment by nstasy** [comment]
i known If delta is zero do not perform relocations, otherwise it performs relocations,

i means that oldbase = (LPVOID)(pImageNtHeader->OptionalHeader.ImageBase) not oldbase = DllPayload.startOfMappedPE;

**Comment by nstasy** [comment]
i known If delta is zero do not perform relocations, otherwise it performs relocations,

i means that oldbase = (LPVOID)(pImageNtHeader->OptionalHeader.ImageBase) not oldbase = DllPayload.startOfMappedPE;

**Comment by naksyn** [comment]
oldbase is not always that value, that is whey there is the control in the first place.
